language: python
python:
  - "2.7"
  - "3.8"
Flask:
  -"3.0.0"
mongoengine:
  -"0.27.0"
Flask-Login:
  - "0.6.3"
Flask-WTF:
  -"1.2.1"
email_validator:
  - "2.2.0"
pymongo:
  - "4.6.0"

install:
  - pip install -r requirements.txt
# command to run tests
script: python -m study_platform.app
