language: python
python:
  - "2.7"
  - "3.8"
  # PyPy versions
  - "pypy"   # currently Python 2.7.18, PyPy 7.3.19
  - "pypy3"  # currently Python 3.10.16,  PyPy 7.3.19# command to install dependencies
  - "Flask"
-"mongoengine"
-"Flask-Login"
-"Flask-WTF"
-"email_validator"
-"pymongo"

install:
  - pip install -r requirements.txt
# command to run tests
script: python -m study_platform.app
